export const PLANS = {
  free: {
    id: 'free',
    name: 'Free',
    price: 0,
    priceId: null,
    annualPriceId: null,
    description: 'Perfect for getting started',
    colour: '#94a3b8',
    limits: {
      bookings_per_month: 30,
      clients: 50,
      staff: 1,
      services: 5,
      campaigns: 0,
      styles: 0,
      inventory: false,
      analytics: 'basic',
      public_booking_page: true,
      reminders: false,
      multi_location: false,
      api_access: false,
      priority_support: false,
      pwa_shortcut: false,
    },
    features: [
      '30 bookings/month',
      '50 client profiles',
      '1 barber',
      '5 services',
      'Basic dashboard',
      'Public booking page',
      'Manual reminders',
    ],
    notIncluded: [
      'Automated reminders',
      'Email marketing',
      'Inventory management',
      'Advanced analytics',
      'Priority support',
    ],
  },
  starter: {
    id: 'starter',
    name: 'Starter',
    price: 19,
    priceId: process.env.STRIPE_STARTER_PRICE_ID,
    annualPriceId: process.env.STRIPE_STARTER_ANNUAL_PRICE_ID,
    description: 'For the solo barber going professional',
    colour: '#6366f1',
    badge: 'Most Popular',
    limits: {
      bookings_per_month: 150,
      clients: 300,
      staff: 2,
      services: 20,
      campaigns: 2,
      styles: 10,
      inventory: false,
      analytics: 'standard',
      public_booking_page: true,
      reminders: true,
      multi_location: false,
      api_access: false,
      priority_support: false,
      pwa_shortcut: false,
    },
    features: [
      '150 bookings/month',
      '300 client profiles',
      '2 barbers',
      '20 services',
      'Automated SMS & email reminders',
      'Public booking page',
      'Standard analytics',
      '2 marketing campaigns/month',
      'No-show protection',
    ],
    notIncluded: [
      'Inventory management',
      'Advanced analytics',
      'Multi-location',
      'Priority support',
    ],
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    price: 39,
    priceId: process.env.STRIPE_PRO_PRICE_ID,
    annualPriceId: process.env.STRIPE_PRO_ANNUAL_PRICE_ID,
    description: 'For busy shops with a growing team',
    colour: '#f59e0b',
    limits: {
      bookings_per_month: -1, // unlimited
      clients: -1,
      staff: 8,
      services: -1,
      campaigns: 10,
      styles: 30,
      inventory: true,
      analytics: 'advanced',
      public_booking_page: true,
      reminders: true,
      multi_location: false,
      api_access: false,
      priority_support: true,
      pwa_shortcut: true,
    },
    features: [
      'Unlimited bookings',
      'Unlimited clients',
      'Up to 8 barbers',
      'Unlimited services',
      'Inventory management',
      'Advanced analytics & reports',
      '10 marketing campaigns/month',
      'Priority support',
      'Staff commissions tracking',
      'Client loyalty tracking',
    ],
    notIncluded: [
      'Multi-location management',
      'API access',
      'White-label option',
    ],
  },
  empire: {
    id: 'empire',
    name: 'Empire',
    price: 79,
    priceId: process.env.STRIPE_EMPIRE_PRICE_ID,
    annualPriceId: process.env.STRIPE_EMPIRE_ANNUAL_PRICE_ID,
    description: 'For multi-chair empire builders',
    colour: '#10b981',
    limits: {
      bookings_per_month: -1,
      clients: -1,
      staff: -1,
      services: -1,
      campaigns: -1,
      styles: -1,
      inventory: true,
      analytics: 'enterprise',
      public_booking_page: true,
      reminders: true,
      multi_location: true,
      api_access: true,
      priority_support: true,
      pwa_shortcut: true,
    },
    features: [
      'Everything in Pro',
      'Unlimited barbers',
      'Multi-location management',
      'Unlimited campaigns',
      'Enterprise analytics',
      'API access',
      'Dedicated account manager',
      'Custom integrations',
      'White-label booking page',
      'SLA guarantee',
    ],
    notIncluded: [],
  },
} as const;

export type PlanId = keyof typeof PLANS;
export type PlanLimits = typeof PLANS[PlanId]['limits'];

/** Returns the PlanId whose monthly or annual priceId matches the given Stripe price ID, or null. */
export function getPlanByPriceId(priceId: string): PlanId | null {
  for (const [key, plan] of Object.entries(PLANS)) {
    if (
      ('priceId'       in plan && plan.priceId       === priceId) ||
      ('annualPriceId' in plan && plan.annualPriceId === priceId)
    ) return key as PlanId
  }
  return null
}
